language: python
python: "3.6"
env:
  - ADDON_ID=metadata.tvmaze
    BRANCH=leia
install:
  - pip install -q -r requirements.txt
  - pip install -q kodi-addon-checker
script:
  - pylint metadata.tvmaze/libs metadata.tvmaze/main.py tests/conftest.py tests/test_actions.py
  - kodi-addon-checker --branch $BRANCH $ADDON_ID
before_deploy:
  - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git
deploy:
  - provider: script
    script: submit-addon -r repo-scrapers -b $BRANCH -s --pull-request -m $ADDON_ID
    on:
      tags: true
notifications:
  email: false
