language: python
env:
  - ADDON_ID=metadata.tvmaze
    BRANCH=leia
matrix:
  include:
    - python: "2.7"
      install:
        - pip install -q -r requirements.txt
      script:
        - pytest

    - python: "3.6"
      install:
        - pip install kodi-addon-checker
      script:
        - kodi-addon-checker --branch $BRANCH $ADDON_ID
      before_deploy:
        - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git
      deploy:
        - provider: script
          script: submit-addon -r repo-scrapers -b $BRANCH -s --pull-request -m $ADDON_ID
          on:
            tags: true
notifications:
  email: false
