language: python
python: "3.8"
env:
  - ADDON_ID=metadata.tvmaze
    BRANCH=leia
install:
  - pip install -q -r requirements.txt
  - pip install -q kodi-addon-checker
script:
  - pylint
  - pytest -v
  - kodi-addon-checker --branch $BRANCH $ADDON_ID
before_deploy:
  - pip install -q git+https://github.com/romanvm/kodi-addon-submitter.git
deploy:
  - provider: script
    script: submit-addon -r repo-scrapers -b $BRANCH -s -m --pull-request $ADDON_ID
    on:
      tags: true
notifications:
  email: false
